# Generated by Django 2.0.7 on 2018-07-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_url',
            field=models.CharField(max_length=200),
        ),
    ]
