# Generated by Django 2.0.7 on 2018-07-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=11)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('qq_account', models.CharField(max_length=20)),
                ('wechat_account', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
