# Generated by Django 2.0.7 on 2018-07-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0003_auto_20180714_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qq_account',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='wechat_account',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
