# Generated by Django 2.0.7 on 2018-07-14 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0004_auto_20180714_0322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
