# Generated by Django 2.0.7 on 2018-07-16 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfoAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='username',
            new_name='user_id',
        ),
    ]
