# Generated by Django 2.0.7 on 2018-07-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=11)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('is_bound_qq', models.BooleanField(default=False)),
                ('is_bound_wechat', models.BooleanField(default=False)),
                ('qq_account', models.CharField(default=None, max_length=20)),
                ('wechat_account', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
